

import 'package:flutter/material.dart';

class LanguageProvider extends ChangeNotifier {
  String _languageCode = 'en';

  String get languageCode => _languageCode;
  bool get isArabic => _languageCode == 'ar';
  bool get isUrdu => _languageCode == 'ur';
  bool get isRTL => _languageCode == 'ar' || _languageCode == 'ur';

  void setLanguage(String code) {
    if (_languageCode == code) return;
    _languageCode = code;
    notifyListeners();
  }

  Map<String, String> get t {
    if (_languageCode == 'ur') return _ur;
    return _languageCode == 'ar' ? _ar : _en;
  }

  // ── Urdu strings ──────────────────────────────────────────────────────────
  static const Map<String, String> _ur = {
    'appName': 'پاک سیل',
    'tagline': 'مارکیٹ آپ کے گھر پر',

    // Bottom nav
    'nav_home': 'ہوم',
    'nav_categories': 'اقسام',
    'nav_post_ad': 'اشتہار لگائیں',
    'nav_saved': 'محفوظ',
    'nav_chat': 'چیٹ',
    'nav_account': 'اکاؤنٹ',

    // Home
    'search_hint': 'پاکستان سیل میں تلاش کریں...',
    'categories': 'اقسام',
    'featured': 'نمایاں',
    'recent': 'حالیہ اشتہارات',
    'see_all': 'سب دیکھیں',

    // Account – guest
    'welcome': 'پاکستان سیل میں خوش آمدید',
    'login_prompt': 'اپنے اشتہارات، پسندیدہ اور پیغامات کے لیے لاگ ان کریں',
    'login': 'لاگ ان',
    'register': 'رجسٹر',
    'browse': 'براؤز',
    'search_listings': 'اشتہارات تلاش کریں',
    'all_categories': 'تمام اقسام',
    'featured_ads': 'نمایاں اشتہارات',
    'job_center': 'جاب سینٹر',
    'browse_jobs': 'نوکریاں تلاش کریں',
    'upload_cv': 'سی وی اپ لوڈ کریں',
    'information': 'معلومات',
    'language': 'زبان',
    'help_support': 'مدد اور سپورٹ',
    'about': 'پاکستان سیل کے بارے میں',
    'privacy_policy': 'پرائیسی پالیسی',

    // Account – logged in
    'my_ads': 'میرے اشتہارات',
    'favorites': 'پسندیدہ',
    'settings': 'سیٹنگز',
    'active_ads': 'فعال اشتہارات',
    'views': 'مناظر',
    'rating': 'درجہ بندی',
    'chats': 'چیٹ',
    'sold_items': 'فروخت شدہ',
    'boost_perf': 'بوسٹ',
    'post_new_ad': 'نیا اشتہار لگائیں',
    'reach_buyers': 'پاکستان میں ہزاروں خریداروں تک پہنچیں',
    'edit': 'ترمیم',
    'boost': 'بوسٹ',
    'delete': 'حذف کریں',
    'view': 'دیکھیں',

    // Settings
    'account_section': 'اکاؤنٹ',
    'edit_profile': 'پروفائل تبدیل کریں',
    'change_password': 'پاس ورڈ تبدیل کریں',
    'verify_phone': 'فون نمبر کی تصدیق کریں',
    'email': 'ای میل',
    'notifications_section': 'اطلاعات',
    'push_notifications': 'پش نوٹیفیکیشنز',
    'price_alerts': 'قیمت میں کمی کی اطلاع',
    'message_alerts': 'پیغام کی اطلاع',
    'email_notifications': 'ای میل نوٹیفیکیشنز',
    'preferences': 'ترجیحات',
    'default_location': 'ڈیفالٹ مقام',
    'currency': 'کرنسی',
    'privacy_legal': 'پرائیسی اور قانونی',
    'privacy_settings': 'پرائیسی سیٹنگز',
    'terms': 'سروس کی شرائط',
    'app_version': 'ایپ ورژن',
    'account_actions': 'اکاؤنٹ کے اقدامات',
    'logout': 'لاگ آؤٹ',
    'delete_account': 'اکاؤنٹ حذف کریں',

    // Common
    'cancel': 'منسوخ',
    'save': 'محفوظ کریں',
    'done': 'مکمل',
    'close': 'بند کریں',
    'update': 'اپ ڈیٹ',
    'verify': 'تصدیق کریں',
    'call': 'کال',
    'chat': 'چیٹ',
    'share': 'شیئر',
    'unverified': 'غیر تصدیق شدہ',
    'current_lang': 'اردو',

    // About
    'about_content':
    'پاکستان سیل پاکستان کی صف اول کی اشتہارات کی مارکیٹ ہے۔ مختلف اقسام میں مصنوعات اور خدمات خریدیں، بیچیں اور اشتہار دیں۔ ہمارا پلیٹ فارم ملک بھر کے خریداروں اور بیچنے والوں کو جوڑتا ہے۔\n\nورژن: 1.0.0\nتیار کردہ: JH IT Zone\nرابطہ: info@jhitzone.com',

    // Privacy
    'privacy_content':
    'ہم آپ کی پرائیسی کا احترام کرتے ہیں۔ آپ کا ذاتی ڈیٹا کبھی بھی تیسرے فریق کو فروخت نہیں کیا جاتا۔ تمام ڈیٹا انکرپٹڈ اور محفوظ طریقے سے محفوظ کیا جاتا ہے۔ آپ کسی بھی وقت سیٹنگز اسکرین سے ڈیٹا حذف کرنے کی درخواست کر سکتے ہیں۔\n\nہم جمع کرتے ہیں: نام، ای میل، فون نمبر، اور اشتہار کی تفصیلات۔ یہ ڈیٹا صرف مارکیٹ پلیس سروس چلانے کے لیے استعمال ہوتا ہے۔',
    'policy_update_title': 'پالیسی اپ ڈیٹ',
    'policy_update_msg': 'ہماری سروس کی شرائط یا پرائیسی پالیسی کو اپ ڈیٹ کر دیا گیا ہے۔ براہ کرم ایپ کا استعمال جاری رکھنے کے لیے جائزہ لیں اور قبول کریں۔',
    'view_policies': 'پالیسیاں دیکھیں',
    'accept': 'قبول کریں',

    // Terms
    'terms_content':
    'پاکستان سیل استعمال کر کے آپ اتفاق کرتے ہیں:\n\n• صرف حقیقی اشتہارات لگائیں\n• دوسرے صارفین کا احترام کریں\n• دھوکہ دہی کی سرگرمیوں میں ملوث نہ ہوں\n• پاکستان کے قانون کی تعمیل کریں\n\nہم کسی بھی ایسے اشتہار کو ہٹانے کا حق محفوظ رکھتے ہیں جو ان شرائط کی خلاف ورزی کرتا ہو۔ بار بار خلاف ورزی کے نتیجے میں اکاؤنٹ معطل کر دیا جائے گا۔',

    // Help
    'help_q1': 'میں اشتہار کیسے لگا سکتا ہوں؟',
    'help_a1': 'نیچے "اشتہار لگائیں" پر ٹیپ کریں، ایک کیٹیگری منتخب کریں، تفصیلات اور تصاویر بھریں، پھر جمع کرائیں۔',
    'help_q2': 'میں بیچنے والے سے کیسے رابطہ کروں؟',
    'help_a2': 'کوئی بھی اشتہار کھولیں اور نیچے کال، واٹس ایپ یا چیٹ بٹن استعمال کریں۔',
    'help_q3': 'میں اشتہار کیسے محفوظ کروں؟',
    'help_a3': 'کسی بھی اشتہار پر ❤️ دل کے آئیکون پر ٹیپ کریں تاکہ اسے اپنے پسندیدہ میں محفوظ کیا جا سکے۔',
    'help_q4': 'میں اشیاء کا موازنہ کیسے کروں؟',
    'help_a4': 'اشتہارات پر "+ موازنہ" پر ٹیپ کریں، پھر ظاہر ہونے والے موازنہ FAB پر ٹیپ کریں۔',

    // CV upload
    'cv_title': 'اپنی سی وی اپ لوڈ کریں',
    'cv_body': 'پاکستان سیل کے اندر براہ راست ملازمتوں کے لیے درخواست دینے کے لیے اپنی سی وی اپ لوڈ کریں۔ آجر آپ کا پروفائل تلاش کر سکتے ہیں اور آپ سے رابطہ کر سکتے ہیں۔\n\nقبول شدہ فارمیٹس: PDF, DOCX\nزیادہ سے زیادہ سائز: 5 MB',

    // Search & Filter
    'search_filter': 'تلاش اور فلٹر',
    'reset_all': 'سب ری سیٹ کریں',
    'basic_search': 'بنیادی تلاش',
    'keywords_hint': 'کلیدی الفاظ...',
    'price': 'قیمت',
    'min_price': 'کم سے کم روپے',
    'max_price': 'زیادہ سے زیادہ روپے',
    'condition': 'حالت',
    'seller_type': 'بیچنے والے کی قسم',
    'location': 'مقام',
    'apply_search': 'تلاش کریں',
    'all': 'تمام',
    'sale': 'فروخت',
    'rent': 'کرایہ',
    'exchange': 'تبادلہ',
    'free': 'مفت',
    'personal': 'ذاتی',
    'business': 'کاروباری',
    'karachi': 'کراچی',
    'lahore': 'لاہور',
    'islamabad': 'اسلام آباد',
    'rawalpindi': 'راولپنڈی',
    'faisalabad': 'فیصل آباد',
    'multan': 'ملتان',
    'peshawar': 'پشاور',
    'quetta': 'کوئٹہ',
    'sialkot': 'سیالکوٹ',
    'gujranwala': 'گوجرانوالہ',
    'sargodha': 'سرگودھا',
    'furniture_&_décor': 'فرنیچر اور سجاوٹ',
    'watercrafts': 'کشتیاں',
    'jewellery': 'زیورات',
    'lifestyle': 'لائف اسٹائل',
    'market': 'مارکیٹ',
    'outdoor_&_leisure': 'آؤٹ ڈور اور تفریح',
    'special_numbers': 'خصوصی نمبر',
    'heavy_equipments': 'بھاری سامان',
    'jobs_center': 'جاب سینٹر',
    'super_ads': 'سپر اشتہارات',
    'vehicles': 'گاڑیاں',
    'properties': 'جائیدادیں',
    'electronics': 'الیکٹرونکس',
    'filtered': 'فلٹر شدہ',
    'results': 'نتائج',
    'select_category': 'کیٹیگری منتخب کریں',
    'ad_details': 'اشتہار کی تفصیلات',
    'title': 'عنوان',
    'phone_number': 'فون نمبر',
    'search_conversations': 'گفتگو تلاش کریں...',
    'no_conversations': 'ابھی تک کوئی گفتگو نہیں',
    'new_message': 'نیا پیغام',
    'search_users': 'صارفین تلاش کریں...',
    'online': 'آن لائن',
    'negotiable_price': 'قیمت قابل گفت و شنید',
    'view_ad': 'اشتہار دیکھیں',
    'type_message': 'پیغام لکھیں...',
    'notifications': 'اطلاعات',
    'notifications_cleared': 'تمام اطلاعات صاف کر دی گئیں',
    'clear_all': 'سب صاف کریں',
    'no_notifications': 'کوئی اطلاع نہیں',
    'notifications_empty_hint': 'جب کچھ آئے گا تو ہم آپ کو مطلع کریں گے',
    'compare_empty': 'موازنہ کی فہرست میں ابھی تک کوئی چیز نہیں ہے',
    'compare': 'موازنہ',
    'menu': 'مینو',
    'error_loading': 'مصنوعات لوڈ کرنے میں غلطی',
    'retry': 'دوبارہ کوشش کریں',
    'clear_favorites': 'سب صاف کریں',
    'sign_in_required': 'لاگ ان ضروری ہے',
    'sign_in_favorites': 'براہ کرم اپنے پسندیدہ اشتہارات دیکھنے کے لیے لاگ ان کریں۔',
    'no_favorites': 'ابھی تک کوئی پسندیدہ نہیں',
    'no_favorites_hint': 'تیز رسائی کے لیے یہاں محفوظ کرنے کے لیے کسی بھی اشتہار پر ❤️ پر ٹیپ کریں',
    'browse_listings': 'اشتہارات براؤز کریں',
    'categories_title': 'اقسام',
    'clear_favorites_confirm': 'تمام پسندیدہ صاف کریں؟',
    'clear_favorites_confirm_msg': 'کیا آپ واقعی اپنے پسندیدہ سے تمام اشیاء کو ہٹانا چاہتے ہیں؟',
    'sold': 'فروخت شدہ',
    'contact': 'رابطہ',
    'featured_label': 'نمایاں',
    'compare_limit': 'موازنہ کی حد ختم ہوگئی (زیادہ سے زیادہ 3)',
    'compare_added': '✓ شامل کر دیا گیا',
    'sign_in_favorites_short': 'براہ کرم پسندیدہ محفوظ کرنے کے لیے لاگ ان کریں',
    // Notifications
    'all_marked_read': 'سب کو پڑھا ہوا نشان زد کر دیا گیا',
    'mark_all_read': 'سب کو پڑھا ہوا نشان زد کریں',
    'login_required': 'لاگ ان ضروری ہے',
    'login_to_notifications': 'بولیوں، پیغامات، قیمتوں میں کمی اور مزید کے لیے اپنی ذاتی اطلاعات دیکھنے کے لیے سائن ان کریں۔',
    'go_to_login': 'لاگ ان پر جائیں',
    'today': 'آج',
    'yesterday': 'کل',
    'earlier': 'پہلے',
    'notif_new_bid': 'نئی بولی لگائی گئی! 🔨',
    'notif_job_application': 'نئی درخواست موصول ہوئی 📋',
    'notif_ad_approved': 'اشتہار منظور ہو گیا ✅',
    'notif_ad_rejected': 'اشتہار مسترد کر دیا گیا ❌',
    'notif_item_sold': 'چیز فروخت ہو گئی 🎉',
    'notif_price_drop': 'قیمت میں کمی کی اطلاع! 📉',
    'notif_bid_outbid': 'آپ سے اونچی بولی لگائی گئی ہے! 🔨',
    'notif_bid_won': 'آپ نے نیلامی جیت لی ہے! 🏆',
    'notif_offer_received': 'آفر موصول ہوئی 💬',
    'notif_job_status': 'درخواست کی اپ ڈیٹ 📄',
    'notif_new_message': 'نیا پیغام 💬',
    'time_just_now': 'ابھی',
    'time_min_ago': 'منٹ پہلے',
    'time_hour_ago': 'گھنٹہ پہلے',
    'time_hours_ago': 'گھنٹے پہلے',
    'time_day_ago': 'دن پہلے',
    'time_days_ago': 'دن پہلے',
    'ad_submitted': 'اشتہار جمع کر دیا گیا 📝',
    'ad_pending_review': 'آپ کا اشتہار جمع کر دیا گیا ہے اور ایڈمن کے جائزے کا منتظر ہے۔',
    'step_category': 'کیٹیگری',
    'step_details': 'تفصیلات',
    'step_photos': 'تصاویر',
    'step_preview': 'پیش نظارہ',
    'added_to_favorites': 'پسندیدہ میں شامل کر دیا گیا ❤️',
    'removed_from_favorites': 'پسندیدہ سے ہٹا دیا گیا',
    'link_copied': 'لنک کلپ بورڈ پر کاپی ہو گیا!',
    'select_category_error': 'براہ کرم پہلے ایک کیٹیگری منتخب کریں',
    'enter_company_error': 'براہ کرم کمپنی کا نام درج کریں',
    'enter_title_error': 'براہ کرم ایک عنوان درج کریں',
    'enter_price_error': 'براہ کرم قیمت درج کریں (یا مفت کے لیے 0)',
    'select_auction_end_error': 'براہ کرم نیلامی کے خاتمے کی تاریخ منتخب کریں',
    'signin_to_post_error': 'اشتہار لگانے کے لیے براہ کرم سائن ان کریں',
    'session_error': 'صارف کا سیشن نہیں ملا۔ براہ کرم دوبارہ سائن ان کریں۔',
    'back': 'پیچھے',
    'submit_ad': 'اشتہار جمع کرائیں',
    'preview_ad': 'اشتہار دیکھیں',
    'next': 'اگلا',
    'reset': 'ری سیٹ',
    'edit_ad': 'اشتہار میں ترمیم کریں',
    'submitting_ad': 'آپ کا اشتہار جمع کیا جا رہا ہے...',
    'call_now': 'ابھی کال کریں',
    'whatsapp': 'واٹس ایپ',
    'loading': 'لوڈ ہو رہا ہے...',
    'language_changed': 'زبان تبدیل کر دی گئی ہے',
  };

  // ── English strings ────────────────────────────────────────────────────────
  static const Map<String, String> _en = {
    // App name
    'appName': 'Pak Sale',
    'tagline': 'THE MARKET AT YOUR HOME',

    // Bottom nav
    'nav_home': 'Home',
    'nav_categories': 'Categories',
    'nav_post_ad': 'Post Ad',
    'nav_saved': 'Saved',
    'nav_chat': 'Chat',
    'nav_account': 'Account',

    // Home
    'search_hint': 'Search in Pak Sale...',
    'categories': 'Categories',
    'featured': 'Featured',
    'recent': 'Recent Listings',
    'see_all': 'See All',

    // Account – guest
    'welcome': 'Welcome to Pak Sale',
    'login_prompt': 'Login to manage your ads, favorites and messages',
    'login': 'Login',
    'register': 'Register',
    'browse': 'BROWSE',
    'search_listings': 'Search Listings',
    'all_categories': 'All Categories',
    'featured_ads': 'Featured Ads',
    'job_center': 'JOB CENTER',
    'browse_jobs': 'Browse Jobs',
    'upload_cv': 'Upload CV',
    'information': 'INFORMATION',
    'language': 'Language',
    'help_support': 'Help & Support',
    'about': 'About Pak Sale',
    'privacy_policy': 'Privacy Policy',

    // Account – logged in
    'my_ads': 'My Ads',
    'favorites': 'Favorites',
    'settings': 'Settings',
    'active_ads': 'Active Ads',
    'views': 'Views',
    'rating': 'Rating',
    'chats': 'Chats',
    'sold_items': 'Sold',
    'boost_perf': 'Boosts',
    'post_new_ad': 'Post a New Ad',
    'reach_buyers': 'Reach thousands of buyers in Pakistan',
    'edit': 'Edit',
    'boost': 'Boost',
    'delete': 'Delete',
    'view': 'View',

    // Settings
    'account_section': 'ACCOUNT',
    'edit_profile': 'Edit Profile',
    'change_password': 'Change Password',
    'verify_phone': 'Verify Phone Number',
    'email': 'Email',
    'notifications_section': 'NOTIFICATIONS',
    'push_notifications': 'Push Notifications',
    'price_alerts': 'Price Drop Alerts',
    'message_alerts': 'Message Alerts',
    'email_notifications': 'Email Notifications',
    'preferences': 'PREFERENCES',
    'default_location': 'Default Location',
    'currency': 'Currency',
    'privacy_legal': 'PRIVACY & LEGAL',
    'privacy_settings': 'Privacy Settings',
    'terms': 'Terms of Service',
    'app_version': 'App Version',
    'account_actions': 'ACCOUNT ACTIONS',
    'logout': 'Logout',
    'delete_account': 'Delete Account',

    // Common
    'cancel': 'Cancel',
    'save': 'Save',
    'done': 'Done',
    'close': 'Close',
    'update': 'Update',
    'verify': 'Verify',
    'call': 'Call',
    'chat': 'Chat',
    'share': 'Share',
    'unverified': 'Unverified',
    'current_lang': 'English',

    // About
    'about_content':
    'Pak Sale is Pakistan\'s leading classified marketplace. Buy, sell and advertise products & services across multiple categories. Our platform connects buyers and sellers across the entire country.\n\nVersion: 1.0.0\nDeveloped by: JH IT Zone\nContact: info@jhitzone.com',

    // Privacy
    'privacy_content':
    'We respect your privacy. Your personal data is never sold to third parties. All data is encrypted and stored securely. You can request data deletion at any time from the settings screen.\n\nWe collect: name, email, phone number, and listing details. This data is used only to operate the marketplace service.',
    'policy_update_title': 'Policy Update',
    'policy_update_msg': 'Our Terms of Service or Privacy Policy have been updated. Please review and accept to continue using the app.',
    'view_policies': 'View Policies',
    'accept': 'Accept',

    // Terms
    'terms_content':
    'By using Pak Sale you agree to:\n\n• Post only genuine listings\n• Respect other users\n• Not engage in fraudulent activity\n• Comply with Pakistan law\n\nWe reserve the right to remove any listing that violates these terms. Repeated violations will result in account suspension.',

    // Help
    'help_q1': 'How do I post an ad?',
    'help_a1': 'Tap "Post Ad" at the bottom, select a category, fill in details and photos, then submit.',
    'help_q2': 'How do I contact a seller?',
    'help_a2': 'Open any listing and use the Call, WhatsApp, or Chat buttons at the bottom.',
    'help_q3': 'How do I save a listing?',
    'help_a3': 'Tap the ❤️ heart icon on any listing to save it to your Favorites.',
    'help_q4': 'How do I compare items?',
    'help_a4': 'Tap "+ Compare" on listings, then tap the Compare FAB that appears.',

    // CV upload
    'cv_title': 'Upload Your CV',
    'cv_body': 'Upload your CV to apply for jobs directly within Pak Sale. Employers can find your profile and contact you.\n\nFormats accepted: PDF, DOCX\nMax size: 5 MB',
    // Search & Filter
    'search_filter': 'Search & Filter',
    'reset_all': 'Reset All',
    'basic_search': 'Basic Search',
    'keywords_hint': 'Keywords...',
    'price': 'Price',
    'min_price': 'Min Rs.',
    'max_price': 'Max Rs.',
    'condition': 'Condition',
    'seller_type': 'Seller Type',
    'location': 'Location',
    'apply_search': 'Apply & Search',
    'all': 'All',
    'sale': 'Sale',
    'rent': 'Rent',
    'exchange': 'Exchange',
    'free': 'Free',
    'personal': 'Personal',
    'business': 'Business',
    'karachi': 'Karachi',
    'lahore': 'Lahore',
    'islamabad': 'Islamabad',
    'rawalpindi': 'Rawalpindi',
    'faisalabad': 'Faisalabad',
    'multan': 'Multan',
    'peshawar': 'Peshawar',
    'quetta': 'Quetta',
    'sialkot': 'Sialkot',
    'gujranwala': 'Gujranwala',
    'sargodha': 'Sargodha',
    'furniture_&_décor': 'Furniture & Décor',
    'watercrafts': 'WaterCrafts',
    'jewellery': 'Jewellery',
    'lifestyle': 'Lifestyle',
    'market': 'Market',
    'outdoor_&_leisure': 'Outdoor & Leisure',
    'special_numbers': 'Special Numbers',
    'heavy_equipments': 'Heavy Equipments',
    'jobs_center': 'Jobs Center',
    'super_ads': 'Super Ads',
    'vehicles': 'Vehicles',
    'properties': 'Properties',
    'electronics': 'Electronics',
    'filtered': 'Filtered',
    'results': 'results',
    'select_category': 'Select Category',
    'ad_details': 'Ad Details',
    'title': 'Title',
    'phone_number': 'Phone Number',
    'search_conversations': 'Search conversations...',
    'no_conversations': 'No conversations yet',
    'new_message': 'New Message',
    'search_users': 'Search users...',
    'online': 'Online',
    'negotiable_price': 'Negotiable price',
    'view_ad': 'View Ad',
    'type_message': 'Type a message...',
    'notifications': 'Notifications',
    'notifications_cleared': 'All notifications cleared',
    'clear_all': 'Clear All',
    'no_notifications': 'No Notifications',
    'notifications_empty_hint': 'We\'ll notify you when something arrives',
    'compare_empty': 'No items in compare list yet',
    'compare': 'Compare',
    'menu': 'Menu',
    'error_loading': 'Error loading products',
    'retry': 'Retry',
    'clear_favorites': 'Clear All',
    'sign_in_required': 'Sign In Required',
    'sign_in_favorites': 'Please sign in to see your favorite listings.',
    'no_favorites': 'No Favorites Yet',
    'no_favorites_hint': 'Tap the ❤️ on any listing to save it here for quick access',
    'browse_listings': 'Browse Listings',
    'categories_title': 'Categories',
    'clear_favorites_confirm': 'Clear All Favorites?',
    'clear_favorites_confirm_msg': 'Are you sure you want to remove all items from your favorites?',
    'sold': 'SOLD',
    'contact': 'Contact',
    'featured_label': 'Featured',
    'compare_limit': 'Compare limit reached (max 3)',
    'compare_added': '✓ Added',
    'sign_in_favorites_short': 'Please sign in to save favorites',
    // Notifications
    'all_marked_read': 'All marked as read',
    'mark_all_read': 'Mark all as read',
    'login_required': 'Login Required',
    'login_to_notifications': 'Sign in to see your personalised notifications for bids, messages, price drops and more.',
    'go_to_login': 'Go to Login',
    'today': 'Today',
    'yesterday': 'Yesterday',
    'earlier': 'Earlier',
    'notif_new_bid': 'New Bid Placed! 🔨',
    'notif_job_application': 'New Application Received 📋',
    'notif_ad_approved': 'Ad Approved ✅',
    'notif_ad_rejected': 'Ad Rejected ❌',
    'notif_item_sold': 'Item Sold 🎉',
    'notif_price_drop': 'Price Drop Alert! 📉',
    'notif_bid_outbid': "You've Been Outbid! 🔨",
    'notif_bid_won': "You Won the Auction! 🏆",
    'notif_offer_received': 'Offer Received 💬',
    'notif_job_status': 'Application Update 📄',
    'notif_new_message': 'New Message 💬',
    'time_just_now': 'Just now',
    'time_min_ago': 'min ago',
    'time_hour_ago': 'hour ago',
    'time_hours_ago': 'hours ago',
    'time_day_ago': 'day ago',
    'time_days_ago': 'days ago',
    'ad_submitted': 'Ad Submitted 📝',
    'ad_pending_review': 'Your ad has been submitted and is pending admin review.',
    'step_category': 'Category',
    'step_details': 'Details',
    'step_photos': 'Photos',
    'step_preview': 'Preview',
    'added_to_favorites': 'Added to favorites ❤️',
    'removed_from_favorites': 'Removed from favorites',
    'link_copied': 'Link copied to clipboard!',
    'select_category_error': 'Please select a category first',
    'enter_company_error': 'Please enter company name',
    'enter_title_error': 'Please enter a title',
    'enter_price_error': 'Please enter a price (or 0 for free)',
    'select_auction_end_error': 'Please select auction end date',
    'signin_to_post_error': 'Please sign in to post an ad',
    'session_error': 'User session not found. Please sign in again.',
    'back': 'Back',
    'submit_ad': 'Submit Ad',
    'preview_ad': 'Preview Ad',
    'next': 'Next',
    'reset': 'Reset',
    'edit_ad': 'Edit Ad',
    'submitting_ad': 'Submitting your ad...',
    'call_now': 'Call Now',
    'whatsapp': 'WhatsApp',
    'loading': 'Loading...',
    'language_changed': 'Language changed to',
  };

  // ── Arabic strings ─────────────────────────────────────────────────────────
  static const Map<String, String> _ar = {
    // App name
    'appName': 'باك سيل',
    'tagline': 'السوق في بيتك',

    // Bottom nav
    'nav_home': 'الرئيسية',
    'nav_categories': 'الفئات',
    'nav_post_ad': 'إضافة إعلان',
    'nav_saved': 'المحفوظات',
    'nav_chat': 'الدردشة',
    'nav_account': 'حسابي',

    // Home
    'search_hint': 'ابحث في قطر سيل...',
    'categories': 'الفئات',
    'featured': 'مميزة',
    'recent': 'أحدث الإعلانات',
    'see_all': 'عرض الكل',

    // Account – guest
    'welcome': 'مرحباً في قطر سيل',
    'login_prompt': 'سجّل دخولك لإدارة إعلاناتك ومفضلتك ورسائلك',
    'login': 'تسجيل الدخول',
    'register': 'إنشاء حساب',
    'browse': 'تصفح',
    'search_listings': 'البحث في الإعلانات',
    'all_categories': 'جميع الفئات',
    'featured_ads': 'الإعلانات المميزة',
    'job_center': 'مركز الوظائف',
    'browse_jobs': 'تصفح الوظائف',
    'upload_cv': 'رفع السيرة الذاتية',
    'information': 'معلومات',
    'language': 'اللغة',
    'help_support': 'المساعدة والدعم',
    'about': 'عن قطر سيل',
    'privacy_policy': 'سياسة الخصوصية',

    // Account – logged in
    'my_ads': 'إعلاناتي',
    'favorites': 'المفضلة',
    'settings': 'الإعدادات',
    'active_ads': 'إعلانات نشطة',
    'views': 'المشاهدات',
    'rating': 'التقييم',
    'post_new_ad': 'إضافة إعلان جديد',
    'reach_buyers': 'تواصل مع آلاف المشترين في قطر',
    'edit': 'تعديل',
    'boost': 'تعزيز',
    'delete': 'حذف',
    'view': 'عرض',

    // Settings
    'account_section': 'الحساب',
    'edit_profile': 'تعديل الملف الشخصي',
    'change_password': 'تغيير كلمة المرور',
    'verify_phone': 'التحقق من رقم الهاتف',
    'email': 'البريد الإلكتروني',
    'notifications_section': 'الإشعارات',
    'push_notifications': 'إشعارات الجوال',
    'price_alerts': 'تنبيهات انخفاض السعر',
    'message_alerts': 'تنبيهات الرسائل',
    'email_notifications': 'إشعارات البريد الإلكتروني',
    'preferences': 'التفضيلات',
    'default_location': 'الموقع الافتراضي',
    'currency': 'العملة',
    'privacy_legal': 'الخصوصية والقانون',
    'privacy_settings': 'إعدادات الخصوصية',
    'terms': 'شروط الخدمة',
    'app_version': 'إصدار التطبيق',
    'account_actions': 'إجراءات الحساب',
    'logout': 'تسجيل الخروج',
    'delete_account': 'حذف الحساب',

    // Common
    'cancel': 'إلغاء',
    'save': 'حفظ',
    'done': 'تم',
    'close': 'إغلاق',
    'update': 'تحديث',
    'verify': 'تحقق',
    'call': 'اتصال',
    'chat': 'دردشة',
    'share': 'مشاركة',
    'unverified': 'غير مُحقَّق',
    'current_lang': 'العربية',

    // About
    'about_content':
    'قطر سيل هو السوق الإلكتروني الرائد في قطر. اشترِ وبِع وأعلن عن المنتجات والخدمات في مختلف الفئات. يربط منصتنا المشترين والبائعين في جميع أنحاء البلاد.\n\nالإصدار: 1.0.0\nالمطوّر: JH IT Zone\nالتواصل: info@jhitzone.com',

    // Privacy
    'privacy_content':
    'نحن نحترم خصوصيتك. لا نبيع بياناتك الشخصية لأطراف ثالثة. جميع البيانات مشفرة ومحفوظة بأمان. يمكنك طلب حذف بياناتك في أي وقت من شاشة الإعدادات.\n\nنجمع: الاسم والبريد الإلكتروني ورقم الهاتف وتفاصيل الإعلانات. تُستخدم هذه البيانات فقط لتشغيل خدمة السوق.',
    'policy_update_title': 'تحديث السياسة',
    'policy_update_msg': 'تم تحديث شروط الخدمة أو سياسة الخصوصية الخاصة بنا. يرجى المراجعة والموافقة للمتابعة في استخدام التطبيق.',
    'view_policies': 'عرض السياسات',
    'accept': 'قبول',

    // Terms
    'terms_content':
    'باستخدامك لقطر سيل، فإنك توافق على:\n\n• نشر إعلانات حقيقية فقط\n• احترام المستخدمين الآخرين\n• عدم الانخراط في أنشطة احتيالية\n• الامتثال لقوانين قطر\n\nنحتفظ بالحق في إزالة أي إعلان ينتهك هذه الشروط. قد يؤدي الانتهاك المتكرر إلى تعليق الحساب.',

    // Help
    'help_q1': 'كيف أنشر إعلانًا؟',
    'help_a1': 'اضغط على "إضافة إعلان" في الأسفل، اختر الفئة، أدخل التفاصيل والصور، ثم أرسل.',
    'help_q2': 'كيف أتواصل مع البائع؟',
    'help_a2': 'افتح أي إعلان واستخدم أزرار الاتصال أو واتساب أو الدردشة في الأسفل.',
    'help_q3': 'كيف أحفظ إعلانًا؟',
    'help_a3': 'اضغط على أيقونة ❤️ في أي إعلان لحفظه في المفضلة.',
    'help_q4': 'كيف أقارن بين المنتجات؟',
    'help_a4': 'اضغط على "+ مقارنة" في الإعلانات، ثم اضغط زر المقارنة الذي يظهر.',

    // CV upload
    'cv_title': 'رفع السيرة الذاتية',
    'cv_body': 'ارفع سيرتك الذاتية للتقدم للوظائف مباشرةً من قطر سيل. يمكن لأصحاب العمل العثور على ملفك الشخصي والتواصل معك.\n\nالصيغ المقبولة: PDF، DOCX\nالحجم الأقصى: 5 ميجابايت',

    // Search & Filter
    'search_filter': 'البحث والتصفية',
    'reset_all': 'إعادة تعيين الكل',
    'basic_search': 'البحث الأساسي',
    'keywords_hint': 'كلمات مفتاحية...',
    'price': 'السعر',
    'min_price': 'أقل سعر',
    'max_price': 'أعلى سعر',
    'condition': 'الحالة',
    'seller_type': 'نوع البائع',
    'location': 'الموقع',
    'apply_search': 'تطبيق وبحث',
    'all': 'الكل',
    'sale': 'للبيع',
    'rent': 'للايجار',
    'exchange': 'تبادل',
    'free': 'مجاني',
    'personal': 'شخصي',
    'business': 'تجاري',
    'doha': 'الدوحة',
    'al_rayyan': 'الريان',
    'lusail': 'لوسيل',
    'al_khor': 'الخور',
    'al_wakrah': 'الوكرة',
    'west_bay': 'الخليج الغربي',
    'furniture_&_décor': 'الأثاث والديكور',
    'watercrafts': 'القوارب واليخوت',
    'jewellery': 'مجوهرات',
    'lifestyle': 'أسلوب حياة',
    'market': 'سوق',
    'outdoor_&_leisure': 'خارج المنزل والترفيه',
    'special_numbers': 'أرقام مميزة',
    'heavy_equipments': 'معدات ثقيلة',
    'jobs_center': 'مركز الوظائف',
    'super_ads': 'إعلانات سوبر',
    'vehicles': 'المركبات',
    'properties': 'العقارات',
    'electronics': 'الإلكترونيات',
    'filtered': 'تمت التصفية',
    'results': 'نتائج',
    'select_category': 'اختر الفئة',
    'ad_details': 'تفاصيل الإعلان',
    'title': 'العنوان',
    'phone_number': 'رقم الهاتف',
    'search_conversations': 'البحث في المحادثات...',
    'no_conversations': 'لا توجد محادثات بعد',
    'new_message': 'رسالة جديدة',
    'search_users': 'البحث عن مستخدمين...',
    'online': 'متصل الآن',
    'negotiable_price': 'السعر قابل للتفاوض',
    'view_ad': 'عرض الإعلان',
    'type_message': 'اكتب رسالة...',
    'notifications': 'الإشعارات',
    'notifications_cleared': 'تم مسح جميع الإشعارات',
    'clear_all': 'مسح الكل',
    'no_notifications': 'لا توجد إشعارات',
    'notifications_empty_hint': 'سنقوم بإخطارك عند وصول أي شيء جديد',
    'compare_empty': 'لا توجد عناصر في قائمة المقارنة بعد',
    'compare': 'مقارنة',
    'menu': 'القائمة',
    'error_loading': 'خطأ في تحميل المنتجات',
    'retry': 'إعادة محاولة',
    'clear_favorites': 'مسح الكل',
    'sign_in_required': 'تسجيل الدخول مطلوب',
    'sign_in_favorites': 'يرجى تسجيل الدخول لرؤية إعلاناتك المفضلة.',
    'no_favorites': 'لا توجد مفضلات بعد',
    'no_favorites_hint': 'اضغط على ❤️ على أي إعلان لحفظه هنا للوصول السريع',
    'browse_listings': 'تصفح الإعلانات',
    'categories_title': 'الفئات',
    'clear_favorites_confirm': 'مسح جميع المفضلات؟',
    'clear_favorites_confirm_msg': 'هل أنت متأكد أنك تريد إزالة جميع العناصر من مفضلاتك؟',
    'sold': 'مباع',
    'contact': 'تواصل',
    'featured_label': 'مميز',
    'compare_limit': 'تم الوصول إلى حد المقارنة (الحد الأقصى 3)',
    'compare_added': '✓ تمت الإضافة',
    'sign_in_favorites_short': 'يرجى تسجيل الدخول لحفظ المفضلات',
    // Notifications
    'all_marked_read': 'تم تحديد الكل كمقروء',
    'mark_all_read': 'تحديد الكل كمقروء',
    'login_required': 'تسجيل الدخول مطلوب',
    'login_to_notifications': 'سجّل دخولك لرؤية إشعاراتك المخصصة للمناقصات والرسائل وانخفاض الأسعار والمزيد.',
    'go_to_login': 'الذهاب لتسجيل الدخول',
    'today': 'اليوم',
    'yesterday': 'أمس',
    'earlier': 'سابقاً',
    'notif_new_bid': 'تم تقديم مناقصة جديدة! 🔨',
    'notif_job_application': 'تم استلام طلب جديد 📋',
    'notif_ad_approved': 'تم الموافقة على الإعلان ✅',
    'notif_ad_rejected': 'تم رفض الإعلان ❌',
    'notif_item_sold': 'تم بيع العنصر 🎉',
    'notif_price_drop': 'تنبيه انخفاض السعر! 📉',
    'notif_bid_outbid': 'تم تجاوز مناقصتك! 🔨',
    'notif_bid_won': 'لقد فزت بالمزاد! 🏆',
    'notif_offer_received': 'تم استلام العرض 💬',
    'notif_job_status': 'تحديث الطلب 📄',
    'notif_new_message': 'رسالة جديدة 💬',
    'time_just_now': 'الآن',
    'time_min_ago': 'دقيقة مضت',
    'time_hour_ago': 'ساعة مضت',
    'time_hours_ago': 'ساعات مضت',
    'time_day_ago': 'يوم مضت',
    'time_days_ago': 'أيام مضت',
    'ad_submitted': 'تم تقديم الإعلان 📝',
    'ad_pending_review': 'تم تقديم إعلانك وهو قيد مراجعة المسؤول.',
    'step_category': 'الفئة',
    'step_details': 'التفاصيل',
    'step_photos': 'الصور',
    'step_preview': 'معاينة',
    'added_to_favorites': 'تمت الإضافة إلى المفضلة ❤️',
    'removed_from_favorites': 'تمت الإزالة من المفضلة',
    'link_copied': 'تم نسخ الرابط!',
    'select_category_error': 'يرجى اختيار الفئة أولاً',
    'enter_company_error': 'يرجى إدخال اسم الشركة',
    'enter_title_error': 'يرجى إدخال العنوان',
    'enter_price_error': 'يرجى إدخال السعر (أو 0 للمجاني)',
    'select_auction_end_error': 'يرجى اختيار تاريخ انتهاء المزاد',
    'signin_to_post_error': 'يرجى تسجيل الدخول لنشر إعلان',
    'session_error': 'لم يتم العثور على جلسة المستخدم. يرجى تسجيل الدخول مرة أخرى.',
    'back': 'رجوع',
    'submit_ad': 'إرسال الإعلان',
    'preview_ad': 'معاينة الإعلان',
    'next': 'التالي',
    'reset': 'إعادة تعيين',
    'edit_ad': 'تعديل الإعلان',
    'submitting_ad': 'جاري إرسال إعلانك...',
    'call_now': 'اتصل الآن',
    'whatsapp': 'واتساب',
    'loading': 'جاري التحميل...',
    'language_changed': 'تم تغيير اللغة إلى',
  };
}