// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoxWNaXedeQ6ayCo2F3H5A_s3PL18uMWM',
    appId: '1:671530950257:web:78db3c1394d32f83ed45d0',
    messagingSenderId: '671530950257',
    projectId: 'qatar-sale',
    authDomain: 'qatar-sale.firebaseapp.com',
    databaseURL: 'https://qatar-sale-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'qatar-sale.firebasestorage.app',
    measurementId: 'G-CDPV9TDN2V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnLOzvbIuuhJahTzi_3fEv0Hf6xV2vkxk',
    appId: '1:671530950257:android:7e6eb6257537330ded45d0',
    messagingSenderId: '671530950257',
    projectId: 'qatar-sale',
    databaseURL: 'https://qatar-sale-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'qatar-sale.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCci5mhoJYvfZc580da8wkh8HYJeCBWF6A',
    appId: '1:671530950257:ios:43c7e74bc78d55cded45d0',
    messagingSenderId: '671530950257',
    projectId: 'qatar-sale',
    databaseURL: 'https://qatar-sale-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'qatar-sale.firebasestorage.app',
    iosBundleId: 'com.example.marketplaceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCci5mhoJYvfZc580da8wkh8HYJeCBWF6A',
    appId: '1:671530950257:ios:43c7e74bc78d55cded45d0',
    messagingSenderId: '671530950257',
    projectId: 'qatar-sale',
    databaseURL: 'https://qatar-sale-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'qatar-sale.firebasestorage.app',
    iosBundleId: 'com.example.marketplaceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDoxWNaXedeQ6ayCo2F3H5A_s3PL18uMWM',
    appId: '1:671530950257:web:ed345c8f200effa9ed45d0',
    messagingSenderId: '671530950257',
    projectId: 'qatar-sale',
    authDomain: 'qatar-sale.firebaseapp.com',
    databaseURL: 'https://qatar-sale-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'qatar-sale.firebasestorage.app',
    measurementId: 'G-2BTKEWFKZ5',
  );
}
